### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by LivingLikeLogan** [aa2g/AA2Install#13]
On startup, i receive a error that says "You don't seem to have AA2 AND/OR AA2Edit(properly) installed. Please install it, use the registry  fixer (If you've already installed it) or manually specify the install path in the preferences." and then crashes. 

Here is the crash dump

Could not load file or assembly '7z.NET, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
   at AA2Install.formMain.refreshModList(Boolean skipReload, String filter)
   at AA2Install.formMain.formMain_Shown(Object sender, EventArgs events) in C:\Users\Admin\Documents\GitHub\AA2Install\AA2Install\formMain.cs:line 1291
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by patrickb8man** [comment]
You haven't extracted everything from the archive. There are some files missing (notably 7z.NET.dll)
