### ISSUE TITLE
.net 4.5 dependency

### ISSUE THREAD

**Issue by katlogic** [aa2g/AA2Install#14]
When running on .NET 4.0 system, it will crash with the following:

```
<?xml version="1.0" encoding="utf-16"?>
<dictionary>
  <item>
    <key>
      <string>message</string>
    </key>
    <value>
      <string>Could not load type 'System.Runtime.CompilerServices.ExtensionAttribute' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.</string>
    </value>
  </item>
  <item>
    <key>
      <string>stacktrace</string>
    </key>
    <value>
      <string>   at System.ModuleHandle.ResolveMethod(RuntimeModule module, Int32 methodToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount)
   at System.ModuleHandle.ResolveMethodHandleInternalCore(RuntimeModule module, Int32 methodToken, IntPtr[] typeInstantiationContext, Int32 typeInstCount, IntPtr[] methodInstantiationContext, Int32 methodInstCount)
   at System.ModuleHandle.ResolveMethodHandleInternal(RuntimeModule module, Int32 methodToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
   at System.Reflection.CustomAttributeData..ctor(RuntimeModule scope, CustomAttributeRecord caRecord)
   at System.Reflection.CustomAttributeData.GetCustomAttributes(RuntimeModule module, Int32 tkTarget)
   at System.Reflection.CustomAttributeData.GetCustomAttributesInternal(RuntimeAssembly target)
   at System.Reflection.RuntimeAssembly.GetCustomAttributesData()
   at System.Reflection.CustomAttributeData.GetCustomAttributes(Assembly target)
   at System.Resources.ManifestBasedResourceGroveler.GetNeutralResourcesLanguage(Assembly a, UltimateResourceFallbackLocation&amp; fallbackLocation)
   at System.Resources.ResourceManager.CommonSatelliteAssemblyInit()
   at System.Resources.ResourceManager..ctor(Type resourceSource)
   at System.ComponentModel.ComponentResourceManager..ctor(Type t)
   at AA2Install.formMain.InitializeComponent() in C:\Users\Admin\Documents\GitHub\AA2Install\AA2Install\formMain.Designer.cs:line 32
   at AA2Install.formMain..ctor() in C:\Users\Admin\Documents\GitHub\AA2Install\AA2Install\formMain.cs:line 1268
   at AA2Install.Program.Main() in C:\Users\Admin\Documents\GitHub\AA2Install\AA2Install\Program.cs:line 27</string>
    </value>
  </item>
  <item>
    <key>
      <string>lsvlog</string>
    </key>
    <value>
      <string>&lt;?xml version="1.0" encoding="utf-16"?&gt;
&lt;ArrayOfLogEntry xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" /&gt;</string>
    </value>
  </item>
</dictionary>
```

Please mention somewhere that the binaries expect .NET 4.5.

**Comment by patrickb8man** [comment]
[v7 beta 2.1 ](https://github.com/aa2g/AA2Install/releases/tag/v7-beta2.1)is built on .NET 4. I'll be sure to add this to the repo description.
