### ISSUE TITLE
try install the first mod and get crash error

### ISSUE THREAD

**Issue by eliasdiury** [aa2g/AA2Install#17]
at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at AA2Install.formMain.IsEnoughFreeSpace(String drivePath, Int64 requiredBytes) in C:\Users\%\GitHub\AA2Install\AA2Install\formMain.cs:line 220
   at AA2Install.formMain.inject(Boolean createBackup, Boolean checkConflicts, Boolean suppressPopups) in C:\Users\%\GitHub\AA2Install\AA2Install\formMain.cs:line 607
   at AA2Install.formMain.btnApply_Click(Object sender, EventArgs e) in C:\Users\%\GitHub\AA2Install\AA2Install\formMain.cs:line 1100
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by PsychoEliteNZ** [comment]
I get the same error: 

Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at AA2Install.formMain.IsEnoughFreeSpace(String drivePath, Int64 requiredBytes) in C:\Users\Admin\Documents\GitHub\AA2Install\AA2Install\formMain.cs:line 220
   at AA2Install.formMain.inject(Boolean createBackup, Boolean checkConflicts, Boolean suppressPopups) in C:\Users\Admin\Documents\GitHub\AA2Install\AA2Install\formMain.cs:line 607
   at AA2Install.formMain.btnApply_Click(Object sender, EventArgs e) in C:\Users\Admin\Documents\GitHub\AA2Install\AA2Install\formMain.cs:line 1100
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Probably the best time to go back to the other installer.
