### ISSUE TITLE
issues installing certain mods

### ISSUE THREAD

**Issue by yuy168** [aa2g/AA2Install#18]
Hey, I'm trying to get this running on WINE in Linux so if that precludes this issue from consideration just close it.

I get this error when trying to install MCP and uncensorship. 3D rooms installs fine, though the others I haven't tried.

`No access to memory location.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.ReadCore(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.FileStream.Read(Byte[] array, Int32 offset, Int32 count)
   at SB3Utility.PartialStream.Read(Byte[] buffer, Int32 offset, Int32 count) in C:\Users\Admin\Documents\GitHub\AA2Install\SB3UtilityPP\ppSubfile.cs:line 125
   at System.Security.Cryptography.CryptoStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.BinaryReader.ReadBytes(Int32 count)
   at SB3Utility.ppSubfile.WriteTo(Stream stream) in C:\Users\Admin\Documents\GitHub\AA2Install\SB3UtilityPP\ppSubfile.cs:line 37
   at AA2Install.formMain.inject(Boolean createBackup, Boolean checkConflicts, Boolean suppressPopups) in C:\Users\Admin\Documents\GitHub\AA2Install\AA2Install\formMain.cs:line 887
   at AA2Install.formMain.btnApply_Click(Object sender, EventArgs e) in C:\Users\Admin\Documents\GitHub\AA2Install\AA2Install\formMain.cs:line 1100
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)`

any help on this would be great.

**Comment by ezdiy** [comment]
Just to chime in to say - you're a very brave anon. AA2I was never meant to run under mono. Best just boot into windows, fix up the pp files, then run the the game in linux.

... And If you look hardly enough, you might find a mega link with the game with all the decensors already applied.

**Comment by yuy168** [comment]
The weird thing is that this *did* work on another installation on a different computer. I have no idea why it is failing here. The problem with that computer was that it didn't have powerful enough graphics to run the game properly.  I might just grab the installation from there as you suggest.

**Comment by patrickb8man** [comment]
Yeah, I didn't really expect anyone to attempt to run this on anything other than windows so it has some OS calls in the program. Enabling XP compatibility in the settings disables some of them, which might be good to keep in mind.

I'm not very well versed in Linux and how it works, so please excuse me if I say something that sound obvious/stupid.

The specific exception you got occurred in the .NET framework and not my code, so it's an issue that I cannot investigate/debug. Have you got the right permissions for the folder that contains AA2install? Running it in administrator mode might help if that's possible in Wine.

Otherwise I don't think there's anything I can do. If it helps, I can build a mono-compatible version of [AA2Pack](https://github.com/aa2g/AA2Install/releases/tag/v1.0.1-pack) if you're not afraid of installing the mods manually.
