### ISSUE TITLE
aainstall v.71 crash

### ISSUE THREAD

**Issue by aethelred175** [aa2g/AA2Install#23]
i just downloaded aainstall and wanna run it, but it crash when i click the exe.. and error dmps shown up in the folder.
i deleted the plugins folder and it still crash,...

i convert the dmp file to txt and this the write
-----------------------------------------------------------------------------------------------------------------
<?xml version="1.0" encoding="utf-16"?>
<dictionary>
  <item>
    <key>
      <string>message</string>
    </key>
    <value>
      <string>Could not load type 'System.Runtime.CompilerServices.ExtensionAttribute' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.</string>
    </value>
  </item>
  <item>
    <key>
      <string>stacktrace</string>
    </key>
    <value>
      <string>   at System.ModuleHandle.ResolveMethod(RuntimeModule module, Int32 methodToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount)
   at System.ModuleHandle.ResolveMethodHandleInternalCore(RuntimeModule module, Int32 methodToken, IntPtr[] typeInstantiationContext, Int32 typeInstCount, IntPtr[] methodInstantiationContext, Int32 methodInstCount)
   at System.ModuleHandle.ResolveMethodHandleInternal(RuntimeModule module, Int32 methodToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
   at System.Reflection.CustomAttributeData..ctor(RuntimeModule scope, CustomAttributeRecord caRecord)
   at System.Reflection.CustomAttributeData.GetCustomAttributes(RuntimeModule module, Int32 tkTarget)
   at System.Reflection.CustomAttributeData.GetCustomAttributesInternal(RuntimeAssembly target)
   at System.Resources.ManifestBasedResourceGroveler.GetNeutralResourcesLanguage(Assembly a, UltimateResourceFallbackLocation&amp; fallbackLocation)
   at System.Resources.ResourceManager.CommonSatelliteAssemblyInit()
   at System.Resources.ResourceManager..ctor(Type resourceSource)
   at System.ComponentModel.ComponentResourceManager..ctor(Type t)
   at AA2Install.formMain.InitializeComponent()
   at AA2Install.formMain..ctor()
   at AA2Install.Program.Main()</string>
    </value>
  </item>
  <item>
    <key>
      <string>lsvlog</string>
    </key>
    <value>
      <string>&lt;?xml version="1.0" encoding="utf-16"?&gt;
&lt;ArrayOfLogEntry xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" /&gt;</string>
    </value>
  </item>
</dictionary>
-----------------------------------------------------------------------------------------------------------

**Comment by aethelred175** [comment]
oh sorry, i didn't read the requirements for aa2install, its just i havn't install .net
