### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by PriestKitty** [aa2g/AA2Install#24]
I added some files to the mod folder and hit refresh while it was running, this was the first time I got the error. Game seems to work fine, only this tool won't run. Whenever I launch it, it spits out the same error (unable to load whichever mod is #101 in the folder and any after) with a resulting fatal error causing the program to crash. Can't upload the dmp file for it, I have the config attached.
[config.json.gz](https://github.com/aa2g/AA2Install/files/3049840/config.json.gz)

The exact details it gives are as follows, copy-pasted;
"Value of '101' is not valid for 'Value'. 'Value' should be between 'minimum' and 'maximum'.
Parameter name: Value
   at System.Windows.Forms.ProgressBar.set_Value(Int32 value)
   at AA2Install.formMain.refreshModList(Boolean skipReload, String filter)
   at AA2Install.formMain.formMain_Shown(Object sender, EventArgs events)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)"

Thanks.

**Comment by Fantasmator** [comment]
I have the exact same issue, tried removing the number 101 mod but it doesn't matter, the program only opens when there are no mods in mod folder, so basically have to install all of my mods in one go, one crash and I have to redo from scratch.
[Image of the crash](https://imgur.com/a/C82Maci)
