### ISSUE TITLE
Can't launch AA2Install

### ISSUE THREAD

**Issue by CamperNQQB** [aa2g/AA2Install#3]
Whenever i try to launch AA2Install i just get a message telling me that it has stopped working.

And this is what the Crashlog says:

<?xml version="1.0" encoding="utf-16"?>
<dictionary>
  <item>
    <key>
      <string>message</string>
    </key>
    <value>
      <string>Could not load type 'System.Runtime.CompilerServices.ExtensionAttribute' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.</string>
    </value>
  </item>
  <item>
    <key>
      <string>stacktrace</string>
    </key>
    <value>
      <string>   at System.ModuleHandle.ResolveMethod(RuntimeModule module, Int32 methodToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount)
   at System.ModuleHandle.ResolveMethodHandleInternalCore(RuntimeModule module, Int32 methodToken, IntPtr[] typeInstantiationContext, Int32 typeInstCount, IntPtr[] methodInstantiationContext, Int32 methodInstCount)
   at System.ModuleHandle.ResolveMethodHandleInternal(RuntimeModule module, Int32 methodToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
   at System.Reflection.CustomAttributeData..ctor(RuntimeModule scope, CustomAttributeRecord caRecord)
   at System.Reflection.CustomAttributeData.GetCustomAttributes(RuntimeModule module, Int32 tkTarget)
   at System.Reflection.CustomAttributeData.GetCustomAttributesInternal(RuntimeAssembly target)
   at System.Reflection.RuntimeAssembly.GetCustomAttributesData()
   at System.Reflection.CustomAttributeData.GetCustomAttributes(Assembly target)
   at System.Resources.ManifestBasedResourceGroveler.GetNeutralResourcesLanguage(Assembly a, UltimateResourceFallbackLocation&amp; fallbackLocation)
   at System.Resources.ResourceManager.CommonSatelliteAssemblyInit()
   at System.Resources.ResourceManager..ctor(Type resourceSource)
   at System.ComponentModel.ComponentResourceManager..ctor(Type t)
   at AA2Install.formMain.InitializeComponent() in C:\Program Files (x86)\Jenkins\jobs\AA2Install\workspace\AA2Install\formMain.Designer.cs:line 32
   at AA2Install.formMain..ctor() in C:\Program Files (x86)\Jenkins\jobs\AA2Install\workspace\AA2Install\formMain.cs:line 1034
   at AA2Install.Program.Main() in C:\Program Files (x86)\Jenkins\jobs\AA2Install\workspace\AA2Install\Program.cs:line 24</string>
    </value>
  </item>
  <item>
    <key>
      <string>lsvlog</string>
    </key>
    <value>
      <string>&lt;?xml version="1.0" encoding="utf-16"?&gt;
&lt;ArrayOfLogEntry xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" /&gt;</string>
    </value>
  </item>
</dictionary>

**Comment by patrickb8man** [comment]
You seem to not have the latest .NET installed.

**Comment by patrickb8man** [comment]
Assumed fixed.
